#!/usr/bin/env python3
"""
SEO Automation Hub
Coordinates Site Health Auditor, Auto Image Optimizer, and Rank Checker.
Writes a daily summary markdown file `seo_health_report.md` in the root folder.
"""

import sys
import datetime
from pathlib import Path

# Add scripts folder to sys.path
SCRIPTS_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPTS_DIR.parent
sys.path.insert(0, str(SCRIPTS_DIR))

from site_health_auditor import audit_site
from auto_image_optimizer import optimize_images
from auto_rank_checker import update_rank_history

REPORT_PATH = PROJECT_ROOT / 'seo_health_report.md'

def run_automation_hub():
    now_str = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    print("Running Site Health Auditor...")
    health_res = audit_site()
    
    print("Running Auto Image Optimizer...")
    image_res = optimize_images()
    
    print("Running Rank Checker...")
    rank_res = update_rank_history()
    
    # Generate Markdown Report
    issues = health_res["issues"]
    total_issues = sum(len(v) for v in issues.values())
    
    report_content = f"""# 📊 Digitacurve SEO & GEO Automation Health Report

*Generated on: `{now_str}`*

---

## 🎯 Executive Summary
- **Overall Site Health Score**: `{100 - min(total_issues * 2, 80)}/100`
- **Total Files Audited**: `{health_res["files_checked"]}`
- **Registered Next.js Routes**: `{health_res["valid_routes_count"]}`
- **Total Audit Issues Detected**: `{total_issues}`

---

## 📈 Keyword Rankings Summary (`{rank_res["date"]}`)

| Keyword | Rank Position | Status |
| :--- | :---: | :---: |
"""
    for kw, pos in rank_res["rankings"].items():
        status = "🟢 Top 3" if isinstance(pos, int) and pos <= 3 else ("🟡 Page 1" if isinstance(pos, int) and pos <= 10 else "🔵 Indexing/Tracked")
        report_content += f"| `{kw}` | **#{pos}** | {status} |\n"

    report_content += f"""
---

## 🖼️ Image Optimization & Geo-Tagging Status
- **Status**: `{image_res["status"].upper()}`
- **Images Converted to WebP**: `{image_res["converted_count"]}`
- **Code References Updated**: `{image_res["references_updated"]}`
- **Target GPS Geo-Coordinates**: `{image_res.get("gps_coordinates", "N/A")}`

---

## 🔍 Site Audit Diagnostics

### 1. Title Tags & Meta Descriptions
- Missing / Unset Titles: `{len(issues["missing_titles"])}`
- Short Titles (<10 chars): `{len(issues["short_titles"])}`
- Missing Meta Descriptions: `{len(issues["missing_meta_descriptions"])}`

### 2. Heading & Structure (`<h1>` Tags)
- Missing or Multiple `<h1>` Issues: `{len(issues["h1_issues"])}`

### 3. Images & Accessibility
- Missing `alt` attributes: `{len(issues["missing_image_alts"])}`

### 4. Schema & JSON-LD Health
- JSON-LD Syntax Errors: `{len(issues["jsonld_errors"])}`

### 5. Broken Internal Links (404s)
- Broken Links Detected: `{len(issues["broken_internal_links"])}`

---

## 🚀 Actionable Recommendations
1. **Request Indexing in GSC**: Ensure all newly published blog URLs are submitted to Google Search Console.
2. **Review Rank History**: Check `seo_rank_history.csv` for keyword movement trends.
3. **Directory Alignment**: Ensure Clutch, GoodFirms, and G2 business profiles match exact NAP details (+91 7572094201).

---
*Report auto-generated by Digitacurve SEO Engine.*
"""
    
    with open(REPORT_PATH, 'w', encoding='utf-8') as f:
        f.write(report_content)
        
    print(f"\nReport successfully generated at: {REPORT_PATH}")

if __name__ == '__main__':
    run_automation_hub()
